/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalMenuRouteImport } from './routes/digital-menu'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminWorkRouteImport } from './routes/admin/work'
import { Route as ServiceServiceIdRouteImport } from './routes/service/$serviceId'
import { Route as ServicesBrandingRouteImport } from './routes/services/branding'
import { Route as ServicesBusinessCardRouteImport } from './routes/services/business-card'
import { Route as ServicesDigitalMenuRouteImport } from './routes/services/digital-menu'
import { Route as ServicesWebsiteRouteImport } from './routes/services/website'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMenuRoute = DigitalMenuRouteImport.update({
  id: '/digital-menu',
  path: '/digital-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkRoute = AdminWorkRouteImport.update({
  id: '/admin/work',
  path: '/admin/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrandingRoute = ServicesBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBusinessCardRoute = ServicesBusinessCardRouteImport.update({
  id: '/business-card',
  path: '/business-card',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDigitalMenuRoute = ServicesDigitalMenuRouteImport.update({
  id: '/digital-menu',
  path: '/digital-menu',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebsiteRoute = ServicesWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-menu': typeof DigitalMenuRoute
  '/services': typeof ServicesRouteWithChildren
  '/work': typeof WorkRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/work': typeof AdminWorkRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/business-card': typeof ServicesBusinessCardRoute
  '/services/digital-menu': typeof ServicesDigitalMenuRoute
  '/services/website': typeof ServicesWebsiteRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-menu': typeof DigitalMenuRoute
  '/services': typeof ServicesRouteWithChildren
  '/work': typeof WorkRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/work': typeof AdminWorkRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/business-card': typeof ServicesBusinessCardRoute
  '/services/digital-menu': typeof ServicesDigitalMenuRoute
  '/services/website': typeof ServicesWebsiteRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-menu': typeof DigitalMenuRoute
  '/services': typeof ServicesRouteWithChildren
  '/work': typeof WorkRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/work': typeof AdminWorkRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/business-card': typeof ServicesBusinessCardRoute
  '/services/digital-menu': typeof ServicesDigitalMenuRoute
  '/services/website': typeof ServicesWebsiteRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/digital-menu'
    | '/services'
    | '/work'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/work'
    | '/service/$serviceId'
    | '/services/branding'
    | '/services/business-card'
    | '/services/digital-menu'
    | '/services/website'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/digital-menu'
    | '/services'
    | '/work'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/work'
    | '/service/$serviceId'
    | '/services/branding'
    | '/services/business-card'
    | '/services/digital-menu'
    | '/services/website'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/digital-menu'
    | '/services'
    | '/work'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/work'
    | '/service/$serviceId'
    | '/services/branding'
    | '/services/business-card'
    | '/services/digital-menu'
    | '/services/website'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DigitalMenuRoute: typeof DigitalMenuRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  WorkRoute: typeof WorkRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminWorkRoute: typeof AdminWorkRoute
  ServiceServiceIdRoute: typeof ServiceServiceIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-menu': {
      id: '/digital-menu'
      path: '/digital-menu'
      fullPath: '/digital-menu'
      preLoaderRoute: typeof DigitalMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/work': {
      id: '/admin/work'
      path: '/admin/work'
      fullPath: '/admin/work'
      preLoaderRoute: typeof AdminWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/branding': {
      id: '/services/branding'
      path: '/branding'
      fullPath: '/services/branding'
      preLoaderRoute: typeof ServicesBrandingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/business-card': {
      id: '/services/business-card'
      path: '/business-card'
      fullPath: '/services/business-card'
      preLoaderRoute: typeof ServicesBusinessCardRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/digital-menu': {
      id: '/services/digital-menu'
      path: '/digital-menu'
      fullPath: '/services/digital-menu'
      preLoaderRoute: typeof ServicesDigitalMenuRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/website': {
      id: '/services/website'
      path: '/website'
      fullPath: '/services/website'
      preLoaderRoute: typeof ServicesWebsiteRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesBrandingRoute: typeof ServicesBrandingRoute
  ServicesBusinessCardRoute: typeof ServicesBusinessCardRoute
  ServicesDigitalMenuRoute: typeof ServicesDigitalMenuRoute
  ServicesWebsiteRoute: typeof ServicesWebsiteRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBrandingRoute: ServicesBrandingRoute,
  ServicesBusinessCardRoute: ServicesBusinessCardRoute,
  ServicesDigitalMenuRoute: ServicesDigitalMenuRoute,
  ServicesWebsiteRoute: ServicesWebsiteRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DigitalMenuRoute: DigitalMenuRoute,
  ServicesRoute: ServicesRouteWithChildren,
  WorkRoute: WorkRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminWorkRoute: AdminWorkRoute,
  ServiceServiceIdRoute: ServiceServiceIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
